-- Run this once in your Supabase project's SQL Editor (left sidebar > SQL Editor > New query).
-- It creates the two tables this site needs and locks them down with Row Level
-- Security (RLS) so the public "anon" key can only ever do what it's supposed to.
--
-- After running this, create Sammy's one admin account: Authentication > Users >
-- Add user, in the Supabase dashboard. That's the only account this site needs -
-- there's no public sign-up.
--
-- Already ran an earlier version of this file (without the "bio" column)?
-- Just run this one extra line instead of the whole script again:
--   alter table community_portfolios add column bio text default '';

-- ============================================================
-- 1. Sammy's own gallery images
-- ============================================================
create table gallery_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text default '',
  category text default '',
  created_at timestamptz not null default now()
);

alter table gallery_images enable row level security;

-- Anyone can view the gallery
create policy "Public can view gallery images"
  on gallery_images for select
  using (true);

-- Only a logged-in user (Sammy - it's the only account that can exist) can
-- add, edit, or remove images
create policy "Authenticated users can manage gallery images"
  on gallery_images for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');


-- ============================================================
-- 2. Community-submitted portfolio links
-- ============================================================
create table community_portfolios (
  id bigint generated by default as identity primary key,
  name text not null,
  bio text default '',
  notion_link text not null,
  submitted_at timestamptz not null default now(),
  approved boolean not null default false
);

alter table community_portfolios enable row level security;

-- Anyone can submit a link, but it always starts out unapproved - this
-- check means nobody can insert a row that's already approved
create policy "Public can submit a portfolio link"
  on community_portfolios for insert
  with check (approved = false);

-- Anyone can see the approved ones - this is the public list on the homepage
create policy "Public can view approved portfolios"
  on community_portfolios for select
  using (approved = true);

-- Sammy (the only authenticated user) can see every submission, including
-- pending ones, and can approve or delete them
create policy "Authenticated users can view all portfolios"
  on community_portfolios for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can update portfolios"
  on community_portfolios for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete portfolios"
  on community_portfolios for delete
  using (auth.role() = 'authenticated');


-- ============================================================
-- 3. Storage bucket for gallery image files
-- ============================================================
insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do nothing;

create policy "Public can view gallery files"
  on storage.objects for select
  using (bucket_id = 'gallery');

create policy "Authenticated users can upload gallery files"
  on storage.objects for insert
  with check (bucket_id = 'gallery' and auth.role() = 'authenticated');

create policy "Authenticated users can delete gallery files"
  on storage.objects for delete
  using (bucket_id = 'gallery' and auth.role() = 'authenticated');
